// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Message string `json:"message"`
}

type SignInPayload struct {
	User  *User  `json:"user"`
	Error *Error `json:"error"`
}

type SignOutPayload struct {
	Error *Error `json:"error"`
}

type User struct {
	Username string `json:"username"`
}
